### ISSUE TITLE
🚀 Up API Changelog

### ISSUE THREAD

**Issue by d11wtq** [up-banking/api#31]
# 🚀 Changelog

Welcome to the Up API Changelog. This is where we'll provide updates to the community about the changes we make to the Up API. If you want to receive all updates to this changelog, click the "Subscribe" button in the Github sidebar.

<div align="center">
  <h2>
    👉   <img src="https://user-images.githubusercontent.com/37948/89483251-ed2bbe80-d7de-11ea-970c-62711b1bef7c.png" width="300" valign="middle" />
  </h2>
</div>

This issue will remain locked, but if you have questions or feedback about any of the changes—or if you're encountering an issue—please go ahead and [create a new issue](https://github.com/up-banking/api/issues/new) and we'll do our best to help.

<div align="center"><a alt="Jump to the latest changelog" href="https://github.com/up-banking/api/issues/31#issuecomment-678079981"><image src="https://user-images.githubusercontent.com/4755785/89597098-7f45cc80-d89c-11ea-8a47-113a47cce1c1.png" width="300" alt="Jump to the latest changelog" /></a></div>

**Comment by d11wtq** [comment]
Notable changes since we launched the Up API last week:

  - [x] 🐛 Various bugfixes and tweaks
  - [x] 📝 Add optional `description` to webhooks
  - [x] 🏷️ Add tags
    - [x] 🏷️ List all tags
    - [x] 🔗 See which tags are associated with a transaction
    - [x] 🔍 Filter transactions by tag
    - [x] 🔗 Add/remove tags to transactions

----

#### 📝 Add optional `description` to webhooks

You can now supply a `description` along with the `url` for your webhooks. This is simply a tool to be used for administration purposes and has no influence on the behaviour of the webhook itself.

Request:

```
POST /api/v1/webhooks
```

``` json
{
  "data": {
    "attributes": {
      "url": "http://example.com/webhook",
      "description": "Something useful for future reference"
    }
  }
}
```

Response: 204 - Created

#### 🏷️ Add tags

We've added various things tag-related to the API.

**List all tags:**

You can fetch a list of all the tags you have in-use.

Request:

```
GET /api/v1/tags
```

Response: 200 - OK

``` json
{
  "data": [
    {
      "type": "tags",
      "id": "Example Tag 1",
      "relationships": {
        "transactions": {
          "links": { "related": "https://api.up.com.au/api/v1/transactions?filter[tag]=Example+Tag+1" }
        }
      }
    },
    {
      "type": "tags",
      "id": "Example Tag 2",
      "relationships": {
        "transactions": {
          "links": { "related": "https://api.up.com.au/api/v1/transactions?filter[tag]=Example+Tag+2" }
        }
      }
    }
  ],
  "links": {
    "prev": null,
    "next": null
  }
}
```

**See which tags are associated with a transaction:**

When you fetch transactions from the API, they now include a `tags` relationship:

Request:

```
GET /api/v1/transactions
```

Response: 200 - OK (surrounding portion of the payload omitted for brevity)

``` json
{
  "relationships": {
    "tags": {
      "data": [
        {"type": "tags", "id": "Example Tag 1"},
        {"type": "tags", "id": "Example Tag 2"}
      ],
      "links": {
        "self": "https://api.up.com.au/api/v1/transactions/xxxyyyzzz/relationships/tags"
      }
    }
  }
}
```

**Filter transactions by tag:**

We've added a new `filter[tag]` query parameter to the "list transactions" endpoints.

Make sure you correctly URL-encode your tags.

Request:

```
GET /api/v1/transactions?filter[tag]=Example+Tag+1
```

**Add/remove tags to transactions:**

You can add or remove multiple tags to a transaction via the Up API. Both of these requests accept the list of tags in the request payload. For UX reasons, the same limits apply within the API as would apply via the Up application.

Request:

```
POST /api/v1/transactions/xxxyyyzzz/relationships/tags
```

```
{
  "data": [
    {"type": "tags", "id": "Example Tag 1"},
    {"type": "tags", "id": "Example Tag 2"}
  ]
}
```

Response: 204 - No Content

Request:

```
DELETE /api/v1/transactions/xxxyyyzzz/relationships/tags
```

```
{
  "data": [
    {"type": "tags", "id": "Example Tag 1"},
    {"type": "tags", "id": "Example Tag 2"}
  ]
}
```

Response: 204 - No Content

More to come... 😎

**Comment by d11wtq** [comment]
A few changes over the last week:

  - ✏️ Minor typo fixes in the docs
  - 📊 [Add categories](https://developer.up.com.au/#categories)
    - 📊  [List all categories](https://developer.up.com.au/#get_categories)
    - 🔗 [See which categories are associated with a transaction](https://developer.up.com.au/#get_transactions_id)
      - See the `category` and `parentCategory` fields in the `relationships` section

We're working on filtering by category and adding/removing categories to/from transactions.

**Comment by d11wtq** [comment]
A couple of goodies:

  - 😎 [Include saver emoji in account `displayName`](https://developer.up.com.au/#get_accounts)
  - 🔍 [Filter transactions by status](https://developer.up.com.au/#get_transactions)

**Comment by d11wtq** [comment]
- ✏️ Minor typo corrections and clarifications in the docs
  - 🔍 [Filter transactions by category](https://developer.up.com.au/#get_transactions)

**Comment by d11wtq** [comment]
- 💕 2Up accounts are now included in the API (this was quietly released late in 2021)
  - 📃 Add `ownershipType` to accounts to distinguish 2Up from Up
  - 🔍 [Filter accounts by `accountType` and `ownershipType`](https://developer.up.com.au/#get_accounts)

**Comment by d11wtq** [comment]
- 📊 [Add ability to categorize/de-categorize transactions](https://developer.up.com.au/#patch_transactions_transactionId_relationships_category)

**Comment by d11wtq** [comment]
- 🐛 Fixed a bug where `filter[tag]` on the transactions API would not return matching payments

**Comment by markbrown4** [comment]
- 🔒 Personal Access Token management in-app
- 💸 [New Transaction fields](https://developer.up.com.au/#get_transactions_id)
  - `performingCustomer` to distinguish between you and your player 2's transactions on 2Up Accounts.
  - `deepLinkURL` to link directly to the receipt screen in-app
  - `transactionType` for the transaction method used e.g. Purchase, BPAY Payment
  - ✏️ `note` for Up High subscribers with notes on their

**Comment by markbrown4** [comment]
- 📷 Add optional `"attachment"` relationship to transactions
- [Retrieve attachment](https://developer.up.com.au/#get_attachments_id)
- [List attachments](https://developer.up.com.au/#get_attachments)
